import pandas as pd
import numpy as np

df_etf = pd.DataFrame(dict(TECH=['Америка', 'yes', 'USD', 'Stock', 'IT', 'TECHA.ME'],
                           TMOS=['Россия', 'no', 'RUB', 'Stock', None, 'TMOSA.ME'],
                           FXUS=['Америка', 'yes', 'USD', 'Stock', None, 'FXUS.ME'],
                           FXCN=['Китай', 'no', 'USD', 'Stock', None, 'FXCN.ME'],
                           SBMX=['Россия', 'no', 'RUB', 'Stock', None, 'SBMX.ME'],
                           FXGD=['Мир', 'yes', 'USD', 'Gold', None, 'FXGD.ME'],
                           TRUR=['Россия', 'no', 'RUB', 'All', None, 'TRURA.ME'],
                           VTBE=['Развив-ся', 'no', 'USD', 'Stock', None, 'VTBEM.ME'],
                           FXRL=['Россия', 'no', 'RUB', 'Stock', None, 'FXRL.ME'],
                           FXIT=['Америка', 'yes', 'USD', 'Stock', 'IT', 'FXIT.ME'],
                           TGLD=['Мир', 'yes', 'USD', 'Gold', None, 'TGLDA.ME'],
                           TUSD=['Америка', 'yes', 'USD', 'All', None, 'TUSDA.ME'],
                           TEUR=['Европа', 'yes', 'EUR', 'All', None, 'TEURA.ME'],
                           SBRB=['Россия', 'no', 'RUB', 'Bond', 'Corp', 'SBRBA.ME'],
                           SBGB=['Россия', 'no', 'RUB', 'Bond', 'OFZ', 'SBGBA.ME'],
                           SBCB=['Россия', 'no', 'USD', 'Bond', 'Corp', 'SBCBA.ME'],
                           SBSP=['Америка', 'yes', 'USD', 'Stock', None, 'SBSPA.ME'],
                           VTBG=['Мир', 'yes', 'USD', 'Gold', None, 'VTBGO.ME'],
                           VTBM=['Россия', 'no', 'RUB', 'Bond', 'OFZ', 'VTBMM.ME'],
                           VTBB=['Россия', 'no', 'RUB', 'Bond', 'Copr', 'VTBBA.ME'],
                           VTBH=['Америка', 'yes', 'USD', 'Bond', 'Corp', 'VTBHY.ME'],
                           VTBU=['Россия', 'no', 'USD', 'Bond', 'Corp', 'VTBUE.ME'],
                           VTBX=['Россия', 'no', 'RUB', 'Stock', None, 'VTBXE.ME'],
                           VTBA=['Америка', 'yes', 'USD', 'Stock', None, 'VTBSN2.ME'],
                           AKMB=['Россия', 'no', 'RUB', 'Bond', 'All', 'AKMBA.ME'],
                           AKNX=['Америка', 'yes', 'USD', 'Stock', 'IT', 'AKNXA.ME'],
                           AKEU=['Европа', 'yes', 'EUR', 'Stock', None, 'AKEUA.ME'],
                           AKSP=['Америка', 'yes', 'USD', 'Stock', None, 'AKSPA.ME'],
                           RUSB=['Россия', 'no', 'USD', 'Bond', 'All', 'RUSB.ME'],
                           RUSE=['Россия', 'no', 'USD', 'Stock', None, 'RUSE.ME'],
                           FXTB=['Америка', 'yes', 'USD', 'Bond', 'OFZ', 'FXTB.ME'],
                           FXMM=['Америка', 'yes', 'RUB', 'Bond', 'OFZ', 'FXMM.ME'],
                           FXRU=['Россия', 'no', 'USD', 'Bond', 'Corp', 'FXRU.ME'],
                           FXRB=['Россия', 'no', 'RUB', 'Bond', 'Corp', 'FXRB.ME'],
                           FXDE=['Германия', 'yes', 'EUR', 'Stock', None, 'FXDE.ME'],
                           FXWO=['Мир', 'yes/no', 'USD', 'Stock', None, 'FXWO.ME'],
                           FXRW=['Мир', 'yes/no', 'RUB', 'Stock', None, 'FXRW.ME']))
